// <auto-generated>
//   AI-Refactored: BotHearingSystem.cs (Beyond Diamond Ultra-Realism, Overlay/Event-Only, June 2025)
//   SYSTEMATICALLY MANAGED. Bulletproof, pooling-optimized, null-free, squad-safe, multiplayer/headless compatible.
//   Realism: Personality-driven hearing, squad filtering, variable auditory delay, and non-robotic scan intervals.
//   MIT License.
// </auto-generated>

namespace AIRefactored.AI.Perception
{
    using System;
    using System.Collections.Generic;
    using AIRefactored.AI.Core;
    using AIRefactored.AI.Helpers;
    using AIRefactored.AI.Memory;
    using AIRefactored.Core;
    using AIRefactored.Pools;
    using EFT;
    using UnityEngine;

    /// <summary>
    /// Squad-aware, humanized bot hearing—personality, stance, caution, and environmental noise.
    /// Overlay/event-only, null-safe, pooled, multiplayer/headless compliant. Ticked only by BotBrain.
    /// Never triggers movement, teleport, or direct action—data only.
    /// </summary>
    public sealed class BotHearingSystem
    {
        #region Constants

        private const float BaseHearingRange = 35f;
        private const float TimeWindow = 3f;
        private const float MinScanJitter = -0.45f;
        private const float MaxScanJitter = 0.75f;
        private const float MinEffectiveRange = 15f;
        private const float MaxEffectiveRange = 55f;

        #endregion

        #region Fields

        private BotOwner _bot;
        private BotComponentCache _cache;
        private float _nextScanTime;
        private float _personalScanJitter;

        #endregion

        #region Initialization

        /// <summary>
        /// Overlay/event-only. Must be called from BotBrain. No background tick.
        /// </summary>
        public void Initialize(BotComponentCache cache)
        {
            if (cache == null || cache.Bot == null)
            {
                Reset();
                return;
            }

            Player player = cache.Bot.GetPlayer;
            if (!EFTPlayerUtil.IsValid(player))
            {
                Reset();
                return;
            }

            _bot = cache.Bot;
            _cache = cache;
            _personalScanJitter = UnityEngine.Random.Range(MinScanJitter, MaxScanJitter);
            _nextScanTime = Time.time + 1f + _personalScanJitter;
        }

        #endregion

        #region Overlay/Event Tick

        /// <summary>
        /// Overlay/event-only: Called ONLY from BotBrain on overlay tick. Never per-frame.
        /// </summary>
        public void Tick(float deltaTime)
        {
            try
            {
                if (!GameWorldHandler.IsSafeToInitialize || _bot == null || _cache == null) return;
                if (!IsActive()) return;

                float now = Time.time;
                if (now < _nextScanTime) return;

                // Next scan interval is irregular (prevents robotic cadence).
                _nextScanTime = now + UnityEngine.Random.Range(1.4f, 2.1f) + _personalScanJitter;

                float hearingRange = GetEffectiveHearingRange(_bot, _cache);
                Vector3 origin = _bot.Position;
                float rangeSqr = hearingRange * hearingRange;

                List<Player> players = null;
                try
                {
                    players = BotMemoryStore.GetNearbyPlayers(origin, hearingRange);
                    int count = players?.Count ?? 0;

                    for (int i = 0; i < count; i++)
                    {
                        Player candidate = players[i];
                        if (!IsAudibleSource(candidate, origin, rangeSqr)) continue;
                        if (HeardSomething(candidate))
                        {
                            Vector3 pos = EFTPlayerUtil.GetPosition(candidate);
                            if (pos.sqrMagnitude > 0.01f)
                                _cache.RegisterHeardSound(pos); // Overlay/event-only, never direct movement
                        }
                    }
                }
                finally
                {
                    if (players != null) TempListPool.Return(players);
                }
            }
            catch (Exception ex)
            {
                Plugin.LoggerInstance.LogError($"[BotHearingSystem] Tick exception: {ex}");
                Reset();
            }
        }

        #endregion

        #region Private Helpers

        /// <summary>
        /// Defensive full reset; called on any logic error.
        /// </summary>
        private void Reset()
        {
            _bot = null;
            _cache = null;
            _nextScanTime = 0f;
            _personalScanJitter = 0f;
        }

        /// <summary>
        /// Fully safe and ready for overlay hearing logic.
        /// </summary>
        private bool IsActive()
        {
            return _bot != null
                && !_bot.IsDead
                && EFTPlayerUtil.IsValid(_bot.GetPlayer)
                && _cache != null
                && _cache.PanicHandler != null
                && !_cache.PanicHandler.IsPanicking;
        }

        /// <summary>
        /// True if bot would detect a sound from this player (fire or step).
        /// </summary>
        private bool HeardSomething(Player source)
        {
            return source != null
                && (BotSoundUtils.DidFireRecently(_bot, source, 1f, TimeWindow) ||
                    BotSoundUtils.DidStepRecently(_bot, source, 1f, TimeWindow));
        }

        /// <summary>
        /// Squad, self, and range checks for hearing.
        /// </summary>
        private bool IsAudibleSource(Player candidate, Vector3 origin, float rangeSqr)
        {
            if (!EFTPlayerUtil.IsValid(candidate)) return false;

            Player self = _bot.GetPlayer;
            if (candidate == self) return false;
            if (IsSameActiveSquad(self, candidate)) return false;

            Vector3 pos = EFTPlayerUtil.GetPosition(candidate);
            return (pos - origin).sqrMagnitude <= rangeSqr;
        }

        /// <summary>
        /// True if players are living members of the same squad (filters own group for realism).
        /// </summary>
        private static bool IsSameActiveSquad(Player a, Player b)
        {
            if (a == null || b == null) return false;
            string ag = a.Profile?.Info?.GroupId;
            string bg = b.Profile?.Info?.GroupId;
            return !string.IsNullOrEmpty(ag) && ag == bg
                && b.HealthController != null && b.HealthController.IsAlive;
        }

        /// <summary>
        /// Computes the effective hearing range for this bot, including personality, stance, caution, and environmental noise.
        /// </summary>
        private static float GetEffectiveHearingRange(BotOwner bot, BotComponentCache cache)
        {
            float awareness = 0.5f, hearing = 0.5f, caution = 0.5f, stanceBias = 0f;

            var profile = cache.AIRefactoredBotOwner?.PersonalityProfile;
            if (profile != null)
            {
                awareness = Mathf.Clamp01(profile.Awareness);
                hearing = Mathf.Clamp01(profile.HearingBias);
                caution = Mathf.Clamp01(profile.Caution);
                stanceBias = Mathf.Clamp(profile.StanceBias, -1.0f, 2.0f);
            }

            float stanceFactor = 1.0f;
            try
            {
                var movement = bot.GetPlayer?.MovementContext;
                if (movement != null)
                {
                    float pose = movement.PoseLevel;
                    if (pose > 20f && pose < 65f) stanceFactor = 1.1f + 0.1f * stanceBias;
                    else if (pose <= 20f) stanceFactor = 1.05f + 0.1f * stanceBias;
                    else stanceFactor = 1.0f + 0.05f * stanceBias;
                }
            }
            catch { }

            float environmentNoise = UnityEngine.Random.Range(0.93f, 1.04f);

            float range = BaseHearingRange
                * (0.90f + 0.14f * awareness + 0.13f * hearing + 0.09f * caution)
                * stanceFactor
                * environmentNoise;

            return Mathf.Clamp(range, MinEffectiveRange, MaxEffectiveRange);
        }

        #endregion
    }
}
