// <auto-generated>
//   AI-Refactored: BotSoundUtils.cs (Supreme Arbitration Overlay/Event Edition, June 2025 – Final Realism Compliance)
//   Bulletproof event/overlay-driven sound awareness logic. No mutation, no error cascade, multiplayer/headless parity.
//   MIT License.
// </auto-generated>

namespace AIRefactored.AI.Helpers
{
    using AIRefactored.Core;
    using EFT;

    /// <summary>
    /// Overlay/event-driven, bulletproof sound awareness filters for AIRefactored bots.
    /// Filters audio by recency, validity, and strict enemy/ally logic.
    /// Pure (no state/mutation), multiplayer/headless safe, never propagates error.
    /// </summary>
    public static class BotSoundUtils
    {
        /// <summary>
        /// Returns true if the given source is not a teammate and fired recently.
        /// Overlay/event only, bulletproof, never throws.
        /// </summary>
        public static bool DidFireRecently(BotOwner self, Player source, float threshold = 1.5f, float now = -1f)
        {
            try
            {
                return EFTPlayerUtil.IsValidBotOwner(self) &&
                       EFTPlayerUtil.IsValid(source) &&
                       EFTPlayerUtil.IsEnemyOf(self, source) &&
                       BotSoundRegistry.FiredRecently(source, threshold, now);
            }
            catch
            {
                return false;
            }
        }

        /// <summary>
        /// Returns true if the given source is not a teammate and stepped recently.
        /// Overlay/event only, bulletproof, never throws.
        /// </summary>
        public static bool DidStepRecently(BotOwner self, Player source, float threshold = 1.2f, float now = -1f)
        {
            try
            {
                return EFTPlayerUtil.IsValidBotOwner(self) &&
                       EFTPlayerUtil.IsValid(source) &&
                       EFTPlayerUtil.IsEnemyOf(self, source) &&
                       BotSoundRegistry.SteppedRecently(source, threshold, now);
            }
            catch
            {
                return false;
            }
        }
    }
}
