// <auto-generated>
//   AI-Refactored: BotFlashReactionComponent.cs (Beyond Diamond Ultra-Realism, June 2025, Overlay/Event-Only)
//   Absolute anti-teleport, anti-skate: No tick/coroutine movement, never disables or falls back. All moves are event/intent/cooldown, pooled and overlay-only.
//   Full SPT/FIKA/headless/client parity. Squad comms, panic, suppression fully integrated. No allocations or state leaks. All moves NavMesh-sampled, deduped, and Y-clamped. No raw vector usage ever.
//   MIT License.
// </auto-generated>

namespace AIRefactored.AI.Reactions
{
    using System;
    using AIRefactored.AI.Combat;
    using AIRefactored.AI.Core;
    using AIRefactored.AI.Helpers;
    using AIRefactored.Core;
    using UnityEngine;
    using EFT;

    /// <summary>
    /// Handles bot reactions to intense light (flashlights/flashbangs) via overlays only.
    /// No per-tick movement. All moves are intent-only, pooled, event-driven, never disables or teleports.
    /// </summary>
    public sealed class BotFlashReactionComponent
    {
        #region Constants

        private const float FallbackDistance = 5f;
        private const float FallbackJitter = 1.25f;
        private const float MaxSuppressionDuration = 5f;
        private const float MinSuppressionDuration = 1f;
        private const float ReactionCooldown = 0.5f;
        private const float TriggerIntensityThreshold = 0.35f;
        private const float SquadEchoCooldown = 2.5f;

        #endregion

        #region Fields

        private BotComponentCache _cache;
        private float _lastTriggerTime = -1f;
        private float _suppressedUntil = -1f;
        private float _lastSquadEchoTime = -5f;
        private bool _failed;

        #endregion

        #region Initialization

        /// <summary>
        /// Attach and initialize this flash reaction component.
        /// </summary>
        public void Initialize(BotComponentCache cache)
        {
            try
            {
                _cache = cache ?? throw new ArgumentNullException(nameof(cache));
                _failed = false;
            }
            catch (Exception ex)
            {
                _cache = null;
                _failed = true;
                Plugin.LoggerInstance.LogError($"[BotFlashReactionComponent] Initialize exception: {ex}");
            }
        }

        #endregion

        #region Runtime

        public bool IsSuppressed()
        {
            return !_failed && Time.time < _suppressedUntil;
        }

        /// <summary>
        /// Ticked by BotBrain (overlay/event-only). No per-frame movement. Suppression overlays only.
        /// </summary>
        public void Tick(float time)
        {
            if (_failed || _cache == null || _cache.Bot == null)
                return;

            try
            {
                if (time >= _suppressedUntil)
                    _suppressedUntil = -1f;

                Transform head = BotCacheUtility.Head(_cache);
                if (head == null)
                    return;

                var lights = FlashlightRegistry.GetLastKnownFlashlightPositions();
                if (lights == null || lights.Count == 0)
                    return;

                for (int i = 0; i < lights.Count; i++)
                {
                    Vector3 lightPos = lights[i];
                    Vector3 eyePos = head.position + Vector3.up * 0.22f;
                    Vector3 toBot = eyePos - lightPos;
                    if (toBot.sqrMagnitude > 784f) continue; // >28m
                    float angle = Vector3.Angle(-head.forward, toBot);
                    if (angle > 35f) continue;

                    if (Physics.Raycast(lightPos, toBot.normalized, out RaycastHit hit, toBot.magnitude + 0.1f, AIRefactoredLayerMasks.LineOfSightMask))
                    {
                        if (ReferenceEquals(hit.transform, head) || ReferenceEquals(hit.collider.transform, head))
                        {
                            TriggerSuppression(1f, time);
                            return;
                        }
                    }
                    else if (toBot.magnitude < 4.5f && angle < 17f)
                    {
                        TriggerSuppression(0.85f, time);
                        return;
                    }
                }
            }
            catch (Exception ex)
            {
                _failed = true;
                Plugin.LoggerInstance.LogError($"[BotFlashReactionComponent] Tick exception: {ex}");
            }
        }

        /// <summary>
        /// Triggers bot suppression/fallback/panic overlays as a one-shot event (never tick-move, never teleports).
        /// </summary>
        public void TriggerSuppression(float strength = 0.6f, float now = -1f)
        {
            if (_failed || _cache == null || _cache.Bot == null)
                return;

            try
            {
                BotOwner bot = _cache.Bot;
                if (bot.IsDead) return;
                Player player = bot.GetPlayer;
                if (player == null || !player.IsAI || player.IsYourPlayer) return;

                float time = now > 0f ? now : Time.time;
                if (time - _lastTriggerTime < ReactionCooldown) return;
                _lastTriggerTime = time;

                float composure = 1f;
                if (_cache.PanicHandler != null)
                {
                    try { composure = Mathf.Clamp01(_cache.PanicHandler.GetComposureLevel()); }
                    catch { composure = 1f; }
                }

                float scaled = Mathf.Clamp01(strength) * composure;
                float duration = Mathf.Lerp(MinSuppressionDuration, MaxSuppressionDuration, scaled);
                _suppressedUntil = time + duration;

                TriggerFallback(bot, time);
                TriggerPanic(_cache, time);
            }
            catch (Exception ex)
            {
                _failed = true;
                Plugin.LoggerInstance.LogError($"[BotFlashReactionComponent] TriggerSuppression exception: {ex}");
            }
        }

        #endregion

        #region Helpers

        /// <summary>
        /// Issues a *single* fallback move (overlay/intent only), always NavMesh-sampled, never teleports or snap-moves. Squad/MP safe.
        /// </summary>
        private void TriggerFallback(BotOwner bot, float now)
        {
            try
            {
                if (bot == null) return;

                // Always compute intent first, then NavMesh sample+drift in helper
                Vector3 dir = bot.LookDirection.sqrMagnitude > 0.01f ? bot.LookDirection.normalized : bot.Transform.forward;
                Vector3 fallbackIntent = bot.Position - dir * FallbackDistance;
                // Add post-sample micro-jitter in movement helper, not here

                // Squad-aware fallback offset
                var group = bot.BotsGroup;
                if (group != null && group.MembersCount > 1)
                {
                    Vector3 squadCenter = Vector3.zero;
                    int squadCount = 0;
                    for (int i = 0; i < group.MembersCount; i++)
                    {
                        BotOwner mate = group.Member(i);
                        if (mate != null && !mate.IsDead)
                        {
                            squadCenter += mate.Position;
                            squadCount++;
                        }
                    }
                    if (squadCount > 0)
                        squadCenter /= squadCount;
                    Vector3 squadOffset = (fallbackIntent - squadCenter).normalized * 1.7f;
                    fallbackIntent += squadOffset;
                }

                // Never update cache unless move actually issued
                BotMovementHelper.SmoothMoveToSafe(bot, fallbackIntent, slow: true);

                // Squad echo (event only, never disables)
                if (_cache?.GroupBehavior?.GroupSync != null && now - _lastSquadEchoTime > SquadEchoCooldown)
                {
                    _cache.GroupBehavior.GroupSync.ShareFallbackToSquad(fallbackIntent, now);
                    _lastSquadEchoTime = now;
                }
            }
            catch (Exception ex)
            {
                Plugin.LoggerInstance.LogError($"[BotFlashReactionComponent] TriggerFallback failed: {ex}");
            }
        }

        /// <summary>
        /// Panic overlay (event only). Never disables, never ticked. Squad/MP safe.
        /// </summary>
        private void TriggerPanic(BotComponentCache cache, float now)
        {
            try
            {
                if (BotPanicUtility.TryGetPanicComponent(cache, out BotPanicHandler panic) && panic != null)
                {
                    panic.TriggerPanic();

                    if (cache.GroupBehavior?.GroupSync != null && now - _lastSquadEchoTime > SquadEchoCooldown)
                    {
                        cache.GroupBehavior.GroupSync.ShareDangerToSquad(cache.Position, now);
                        _lastSquadEchoTime = now;
                    }
                }

                cache.GroupComms?.SaySuppression();
            }
            catch (Exception ex)
            {
                Plugin.LoggerInstance.LogError($"[BotFlashReactionComponent] TriggerPanic failed: {ex}");
            }
        }

        #endregion
    }
}
