// <auto-generated>
//   AI-Refactored: TempListPool.cs (Ultimate Arbitration, Max-Realism, Zero-Alloc Edition – June 2025)
//   Bulletproof generic List<T> pooling for ultra-high-performance AI and world logic.
//   Thread-safe, teardown/reload safe, diagnostics-ready, AI-Refactored pooling compliant.
//   MIT License.
// </auto-generated>

namespace AIRefactored.Pools
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Centralized pool for temporary <see cref="List{T}"/> reuse.
    /// Prevents GC churn in high-frequency AI/world logic. Thread-safe, teardown/reload safe, diagnostics-ready.
    /// </summary>
    public static class TempListPool
    {
        private static readonly Dictionary<Type, Stack<object>> PoolByType = new Dictionary<Type, Stack<object>>(128);
        private static readonly object SyncRoot = new object();
        private static int _totalRented, _totalReturned, _totalPooled;

        static TempListPool()
        {
            // DomainUnload safe teardown for hot-reload scenarios (editor, SPT, FIKA).
            try
            {
                AppDomain.CurrentDomain.DomainUnload += (_, __) => ClearAll();
            }
            catch { }
        }

        /// <summary>
        /// Retrieves a pooled list of type <typeparamref name="T"/> (never null, always cleared).
        /// </summary>
        public static List<T> Rent<T>()
        {
            lock (SyncRoot)
            {
                if (PoolByType.TryGetValue(typeof(T), out var stack) && stack.Count > 0)
                {
                    _totalRented++;
                    return (List<T>)stack.Pop();
                }
            }
            _totalRented++;
            return new List<T>();
        }

        /// <summary>
        /// Retrieves a pooled list of type <typeparamref name="T"/> with guaranteed minimum capacity.
        /// </summary>
        public static List<T> Rent<T>(int minCapacity)
        {
            List<T> list = Rent<T>();
            if (list.Capacity < minCapacity)
                list.Capacity = minCapacity;
            return list;
        }

        /// <summary>
        /// Returns a list to the pool after clearing it. Null/duplicate returns are ignored.
        /// </summary>
        public static void Return<T>(List<T> list)
        {
            if (list == null)
                return;

            list.Clear();
            lock (SyncRoot)
            {
                if (!PoolByType.TryGetValue(typeof(T), out var stack))
                {
                    stack = new Stack<object>(32);
                    PoolByType[typeof(T)] = stack;
                }
                stack.Push(list);
                _totalReturned++;
                _totalPooled = stack.Count;
            }
        }

        /// <summary>
        /// Prewarms the pool for a specific type with a fixed number of empty lists.
        /// </summary>
        public static void Prewarm<T>(int count)
        {
            if (count <= 0)
                return;

            lock (SyncRoot)
            {
                if (!PoolByType.TryGetValue(typeof(T), out var stack))
                {
                    stack = new Stack<object>(count);
                    PoolByType[typeof(T)] = stack;
                }
                for (int i = 0; i < count; i++)
                    stack.Push(new List<T>());
                _totalPooled = stack.Count;
            }
        }

        /// <summary>
        /// Clears all pooled lists across all types. Use during teardown or reload.
        /// </summary>
        public static void ClearAll()
        {
            lock (SyncRoot)
            {
                foreach (var stack in PoolByType.Values)
                    stack.Clear();
                PoolByType.Clear();
                _totalPooled = 0;
                _totalRented = 0;
                _totalReturned = 0;
            }
        }

        /// <summary>
        /// Returns pooling stats for diagnostics/monitoring.
        /// </summary>
        public static (int typePools, int totalPooled, int totalRented, int totalReturned) GetStats()
        {
            lock (SyncRoot)
            {
                int pooled = 0;
                foreach (var stack in PoolByType.Values)
                    pooled += stack.Count;
                return (PoolByType.Count, pooled, _totalRented, _totalReturned);
            }
        }
    }
}
